create table public.trainer_market_news_pool (
  market_date date not null,
  publish_order smallint not null check (publish_order between 1 and 5),
  symbol text not null references public.trainer_market_symbols(symbol),
  headline text not null check (char_length(headline) between 4 and 60),
  body text not null check (char_length(body) between 30 and 300),
  sentiment smallint not null check (sentiment between -2 and 2),
  primary key (market_date, publish_order),
  unique (market_date, symbol)
);

alter table public.trainer_market_news_pool enable row level security;

with stories(day_offset, context, entries) as (
  values
    (0, '관동 연합 탐사대가 붉은 협곡에서 오래된 발전 광맥을 확인했어요. 다음 달 체육관 순회전의 전력 확보 여부가 이 조사에 달렸어요.', '[{"symbol":"SILPH","headline":"협곡 신호 해독기 투입","body":"실프는 미확인 파장을 읽을 해독기를 현장에 보냈어요.","sentiment":1},{"symbol":"BALL","headline":"탐사 장비용 볼 증산","body":"몬스터볼 팩토리는 탐사용 내구 볼의 추가 생산을 시작했어요.","sentiment":1},{"symbol":"CENTER","headline":"현장 진료소 대기","body":"포켓몬센터는 탐사대 귀환 시간에 맞춰 이동 진료소를 준비했어요.","sentiment":0},{"symbol":"CELADON","headline":"탐사 장비 팝업 예약","body":"금빛시티 백화점은 등산 장비 팝업의 입점 예약을 받기 시작했어요.","sentiment":1},{"symbol":"OAK","headline":"광맥 표본 분석 착수","body":"오박사연구소는 광맥 표본의 생태 반응 분석을 먼저 맡았어요.","sentiment":2}]'::jsonb),
    (1, '밤사이 협곡 입구의 자기장이 나침반을 흔들었어요. 탐사대는 우회로를 확보할 때까지 인원을 나눠 이동하기로 했어요.', '[{"symbol":"BALL","headline":"우회로 운반 상자 긴급 배치","body":"몬스터볼 팩토리는 충격을 줄이는 운반 상자를 우회로에 먼저 보냈어요.","sentiment":-1},{"symbol":"CENTER","headline":"자기장 멀미 상담 창구","body":"포켓몬센터는 어지럼 증상 안내와 회복 부스를 늘렸어요.","sentiment":1},{"symbol":"CELADON","headline":"방한 물자 코너 확대","body":"금빛시티 백화점은 갑작스러운 야간 대기에 맞춰 방한 물자를 보충했어요.","sentiment":1},{"symbol":"OAK","headline":"자기장 안전선 재측정","body":"오박사연구소는 야생 포켓몬 이동로와 겹치는 구간을 다시 표시했어요.","sentiment":1},{"symbol":"ROCKET","headline":"임시 물류차량 지원","body":"로켓단 홀딩스는 접근이 쉬운 남쪽 길에 임시 물류차량을 투입했어요.","sentiment":1}]'::jsonb),
    (2, '해독된 기록에는 협곡 발전 장치가 일정한 박자에만 안정된다는 내용이 있었어요. 관동 곳곳에서 박자를 맞출 장비 주문이 들어오기 시작했어요.', '[{"symbol":"SILPH","headline":"발전 장치 박자 해독","body":"실프는 기록 속 진동 주기를 휴대용 측정기에 옮겼어요.","sentiment":2},{"symbol":"CENTER","headline":"야간 회복실 예약 증가","body":"포켓몬센터는 탐사대 교대 근무에 맞춰 회복실 인력을 조정했어요.","sentiment":1},{"symbol":"CELADON","headline":"박자등 장식 주문 몰려","body":"금빛시티 백화점은 탐사 응원용 박자등 주문을 별도 창구로 받았어요.","sentiment":1},{"symbol":"OAK","headline":"고대 장치 원리 공개","body":"오박사연구소는 장치가 포켓몬의 걸음과 공명할 가능성을 알렸어요.","sentiment":2},{"symbol":"ROCKET","headline":"장비 주문 경쟁 심화","body":"로켓단 홀딩스는 급한 주문이 몰리자 납기 안내를 보수적으로 바꿨어요.","sentiment":-1}]'::jsonb),
    (3, '협곡 상공에 비구름이 모이며 개통식 일정이 이틀 늦춰졌어요. 탐사대는 장비를 지키는 동안 마을별 대기 계획을 세우고 있어요.', '[{"symbol":"SILPH","headline":"방수 통신망 점검","body":"실프는 비가 와도 끊기지 않도록 중계기를 낮은 지대로 옮겼어요.","sentiment":0},{"symbol":"BALL","headline":"방수 볼 포장 전환","body":"몬스터볼 팩토리는 현장 물량을 방수 포장으로 다시 묶었어요.","sentiment":0},{"symbol":"CELADON","headline":"개통식 행사 이틀 연기","body":"금빛시티 백화점은 협곡 특산품 행사를 안전 점검 뒤로 미뤘어요.","sentiment":-1},{"symbol":"OAK","headline":"비구름 관측팀 파견","body":"오박사연구소는 번개 포켓몬의 이동을 관찰할 팀을 보냈어요.","sentiment":1},{"symbol":"ROCKET","headline":"대기 물류비 부담","body":"로켓단 홀딩스는 차량 대기 시간이 늘어 일부 노선을 합쳤어요.","sentiment":-1}]'::jsonb),
    (4, '비가 그친 뒤 협곡 입구에서 반짝이는 광석 조각이 발견됐어요. 소문을 들은 여행객이 몰리며 주변 상점과 숙소가 빠르게 채워지고 있어요.', '[{"symbol":"SILPH","headline":"광석 반응 기록기 공개","body":"실프는 광석 가까이에서만 켜지는 기록기를 시연했어요.","sentiment":1},{"symbol":"BALL","headline":"여행객용 포획 세트 인기","body":"몬스터볼 팩토리의 초보 탐험 세트 주문이 늘었어요.","sentiment":1},{"symbol":"CENTER","headline":"혼잡 시간 안내 강화","body":"포켓몬센터는 여행객이 몰리는 시간대의 대기 안내를 늘렸어요.","sentiment":0},{"symbol":"OAK","headline":"광석 채집 자제 요청","body":"오박사연구소는 생태 조사 전 무분별한 채집을 삼가 달라고 알렸어요.","sentiment":-1},{"symbol":"ROCKET","headline":"숙소 배송 노선 확대","body":"로켓단 홀딩스는 협곡 인근 숙소까지 소형 배송 노선을 늘렸어요.","sentiment":1}]'::jsonb),
    (5, '탐사대는 첫 안전 통로를 열었지만 바닥의 미세한 떨림을 감지했어요. 오늘은 사람보다 장비와 관측 기록을 먼저 통과시키기로 했어요.', '[{"symbol":"SILPH","headline":"미세 진동 경보 설정","body":"실프는 통로 바닥에 진동 경보기를 촘촘히 설치했어요.","sentiment":1},{"symbol":"BALL","headline":"완충 운반 볼 납품","body":"몬스터볼 팩토리는 표본 운반용 완충 볼을 우선 납품했어요.","sentiment":1},{"symbol":"CENTER","headline":"구조팀 교대 훈련","body":"포켓몬센터는 긴급 이송을 위한 구조팀 교대 훈련을 마쳤어요.","sentiment":1},{"symbol":"CELADON","headline":"현장 관람권 판매 보류","body":"금빛시티 백화점은 안전 통로가 완전히 열릴 때까지 관람권 판매를 멈췄어요.","sentiment":-1},{"symbol":"ROCKET","headline":"창고 출고 순서 조정","body":"로켓단 홀딩스는 흔들림에 약한 물품의 출고 순서를 뒤로 돌렸어요.","sentiment":0}]'::jsonb),
    (6, '진동 기록을 겹쳐 보니 광맥이 협곡 아래의 오래된 전력망과 이어져 있었어요. 마을 대표들은 전력을 나누는 규칙을 먼저 만들자고 모였어요.', '[{"symbol":"SILPH","headline":"전력망 지도 복원","body":"실프는 끊긴 전력선의 위치를 지도 위에 다시 표시했어요.","sentiment":2},{"symbol":"BALL","headline":"공장 절전 운전 검토","body":"몬스터볼 팩토리는 새 전력망 시험 동안 공장 전력을 조절하기로 했어요.","sentiment":0},{"symbol":"CENTER","headline":"회복 장비 전력 우선 요청","body":"포켓몬센터는 회복 장비에 필요한 최소 전력을 마을 회의에 전달했어요.","sentiment":1},{"symbol":"CELADON","headline":"상점가 공동 조명안 제안","body":"금빛시티 백화점은 상점가가 함께 쓸 야간 조명안을 내놨어요.","sentiment":1},{"symbol":"OAK","headline":"전력망 생태 영향 조사","body":"오박사연구소는 전력선 주변 포켓몬의 서식 변화를 조사해요.","sentiment":1}]'::jsonb),
    (7, '마을 회의에서 전력 시험일이 정해지자 협곡 주변 예약이 한꺼번에 늘었어요. 다만 좁은 북쪽 길의 운반량 제한이 새로운 변수로 남았어요.', '[{"symbol":"BALL","headline":"북쪽 길 출하량 제한","body":"몬스터볼 팩토리는 큰 상자를 남쪽 집하장으로 돌리기 시작했어요.","sentiment":-1},{"symbol":"CENTER","headline":"시험일 진료 인력 확보","body":"포켓몬센터는 예약 증가에 맞춰 지원 인력을 모집했어요.","sentiment":1},{"symbol":"CELADON","headline":"시험일 응원 상점가 구성","body":"금빛시티 백화점은 지역 상점과 공동 응원 코너를 꾸렸어요.","sentiment":1},{"symbol":"OAK","headline":"통행량 생태 기준 발표","body":"오박사연구소는 야생 포켓몬 길을 비우는 시간대를 발표했어요.","sentiment":1},{"symbol":"ROCKET","headline":"남쪽 집하장 계약 체결","body":"로켓단 홀딩스는 남쪽 길 집하장 사용 계약을 서둘러 맺었어요.","sentiment":2}]'::jsonb),
    (8, '짙은 안개가 협곡에 내려앉아 첫 전력 시험이 짧게 끝났어요. 장치는 멈췄지만 기록된 빛의 색이 예상과 달라 연구진의 관심이 커졌어요.', '[{"symbol":"SILPH","headline":"안개 속 광파장 수집","body":"실프는 짧은 시험 동안 나온 광파장 데이터를 모두 저장했어요.","sentiment":1},{"symbol":"CENTER","headline":"안개 길 안내 표지 추가","body":"포켓몬센터는 길을 잃은 여행객을 위한 안내 표지를 늘렸어요.","sentiment":0},{"symbol":"CELADON","headline":"우천 취소 상품 교환","body":"금빛시티 백화점은 취소된 체험 상품의 교환 기간을 연장했어요.","sentiment":-1},{"symbol":"OAK","headline":"예상 밖 빛 색 분석","body":"오박사연구소는 빛의 색이 희귀 광물과 닮았다고 설명했어요.","sentiment":2},{"symbol":"ROCKET","headline":"안개 배송 지연 공지","body":"로켓단 홀딩스는 안전을 위해 일부 배송 시간을 늦췄어요.","sentiment":-1}]'::jsonb),
    (9, '빛의 색을 따라가자 협곡 바깥의 낡은 중계탑이 반응했어요. 고장 난 탑을 고치면 마을 전력망도 더 안정될 수 있다는 기대가 생겼어요.', '[{"symbol":"SILPH","headline":"낡은 중계탑 복구 참여","body":"실프는 중계탑의 손상 부품을 교체할 기술자를 보냈어요.","sentiment":2},{"symbol":"BALL","headline":"복구팀 안전 볼 공급","body":"몬스터볼 팩토리는 높은 곳 작업용 안전 볼을 지원했어요.","sentiment":1},{"symbol":"CELADON","headline":"중계탑 전망 코너 기획","body":"금빛시티 백화점은 복구 뒤 열릴 전망 코너를 기획했어요.","sentiment":1},{"symbol":"OAK","headline":"탑 주변 둥지 이전","body":"오박사연구소는 중계탑의 포켓몬 둥지를 안전한 곳으로 옮겼어요.","sentiment":1},{"symbol":"ROCKET","headline":"복구 자재 운송 수주","body":"로켓단 홀딩스는 무거운 복구 자재 운송을 맡았어요.","sentiment":1}]'::jsonb),
    (10, '중계탑 복구 중 예상보다 많은 녹슨 부품이 발견됐어요. 시험 일정은 유지됐지만 예비 부품을 구하는 쪽이 분주해졌어요.', '[{"symbol":"SILPH","headline":"예비 중계 부품 확보","body":"실프는 호환 가능한 부품을 주변 도시에서 급히 모았어요.","sentiment":0},{"symbol":"BALL","headline":"부품 운반 상자 재배치","body":"몬스터볼 팩토리는 작은 부품이 섞이지 않도록 운반 상자를 나눴어요.","sentiment":0},{"symbol":"CENTER","headline":"고소 작업 회복 지원","body":"포켓몬센터는 높은 곳 작업 뒤 쉴 회복 부스를 현장에 열었어요.","sentiment":1},{"symbol":"OAK","headline":"녹슨 부품 성분 분석","body":"오박사연구소는 오래된 부품에 남은 광물 성분을 조사했어요.","sentiment":0},{"symbol":"ROCKET","headline":"야간 운송 추가 편성","body":"로켓단 홀딩스는 예비 부품을 위해 야간 운송을 한 차례 더 편성했어요.","sentiment":1}]'::jsonb),
    (11, '중계탑이 다시 켜지자 협곡 광맥의 박자가 마을 시계와 맞아떨어졌어요. 탐사대는 작은 전력 시험을 주민 공개 행사로 바꾸기로 했어요.', '[{"symbol":"SILPH","headline":"마을 시계 동기화 성공","body":"실프는 중계탑 신호를 마을 시계와 맞추는 데 성공했어요.","sentiment":2},{"symbol":"BALL","headline":"공개 시험용 체험 볼 준비","body":"몬스터볼 팩토리는 어린 트레이너용 체험 볼을 준비했어요.","sentiment":1},{"symbol":"CENTER","headline":"공개 행사 진료 부스","body":"포켓몬센터는 행사장 안에 간단한 진료 부스를 꾸렸어요.","sentiment":1},{"symbol":"CELADON","headline":"협곡 공개 행사 입점","body":"금빛시티 백화점은 지역 장인들과 행사 입점을 확정했어요.","sentiment":2},{"symbol":"ROCKET","headline":"관람객 셔틀 노선 신설","body":"로켓단 홀딩스는 역과 협곡을 잇는 셔틀 노선을 만들었어요.","sentiment":2}]'::jsonb),
    (12, '공개 시험 전날 광맥 근처에서 야생 포켓몬 무리가 길을 막았어요. 연구진은 소리를 줄이고 이동 시간을 바꾸는 방식으로 공존을 택했어요.', '[{"symbol":"SILPH","headline":"저소음 신호 모드 적용","body":"실프는 중계기의 경고음을 빛 신호로 바꿨어요.","sentiment":1},{"symbol":"BALL","headline":"포획 대신 유도 장비 제공","body":"몬스터볼 팩토리는 무리를 해치지 않는 유도 장비를 내놨어요.","sentiment":1},{"symbol":"CENTER","headline":"야생 포켓몬 관찰 진료팀","body":"포켓몬센터는 지친 야생 포켓몬을 살필 팀을 대기시켰어요.","sentiment":1},{"symbol":"CELADON","headline":"행사장 소음 규칙 공지","body":"금빛시티 백화점은 입점 상인에게 소음 제한을 안내했어요.","sentiment":0},{"symbol":"OAK","headline":"이동 시간표 재설계","body":"오박사연구소는 무리의 이동이 끝난 뒤 시험을 시작하도록 조정했어요.","sentiment":2}]'::jsonb),
    (13, '공개 시험은 안정적으로 끝났지만 광맥의 빛이 잠깐 보랏빛으로 바뀌었어요. 다음 시험에서는 더 큰 부하를 걸어 원인을 확인하기로 했어요.', '[{"symbol":"BALL","headline":"고부하 시험용 볼 예약","body":"몬스터볼 팩토리는 장비 보호용 특수 볼 예약을 받기 시작했어요.","sentiment":1},{"symbol":"CENTER","headline":"시험 뒤 휴식 구역 확대","body":"포켓몬센터는 장시간 대기한 트레이너를 위해 휴식 구역을 넓혔어요.","sentiment":1},{"symbol":"CELADON","headline":"보랏빛 조명 상품 인기","body":"금빛시티 백화점은 시험에서 본 색을 닮은 조명 상품을 늘렸어요.","sentiment":1},{"symbol":"OAK","headline":"보랏빛 반응 원인 추적","body":"오박사연구소는 희귀 광물보다 생태 반응 가능성에 무게를 뒀어요.","sentiment":2},{"symbol":"ROCKET","headline":"특수 장비 대여 조건 강화","body":"로켓단 홀딩스는 고부하 장비의 대여 점검 항목을 늘렸어요.","sentiment":0}]'::jsonb),
    (14, '고부하 시험을 앞두고 협곡 인근의 전력 사용량이 빠르게 올랐어요. 마을은 밤 시간대의 불필요한 조명을 줄이는 공동 약속을 시작했어요.', '[{"symbol":"SILPH","headline":"전력 사용 알림판 설치","body":"실프는 마을별 사용량을 보여 주는 알림판을 설치했어요.","sentiment":1},{"symbol":"CENTER","headline":"회복 장비 절전 점검","body":"포켓몬센터는 진료 품질을 해치지 않는 절전 순서를 점검했어요.","sentiment":0},{"symbol":"CELADON","headline":"야간 조명 일부 소등","body":"금빛시티 백화점은 공동 약속에 맞춰 외부 조명을 줄였어요.","sentiment":-1},{"symbol":"OAK","headline":"전력과 생태 기록 비교","body":"오박사연구소는 전력 사용량과 야행성 포켓몬 기록을 비교했어요.","sentiment":1},{"symbol":"ROCKET","headline":"집하장 운행 시간 조정","body":"로켓단 홀딩스는 전력 피크를 피해 집하장 운행 시간을 바꿨어요.","sentiment":0}]'::jsonb),
    (15, '시험 직전 장비 상자 하나가 잘못된 길로 전달됐지만, 추적표 덕분에 해질 무렵 되찾았어요. 책임을 묻기보다 인수 절차를 고치자는 목소리가 커졌어요.', '[{"symbol":"SILPH","headline":"장비 추적표 공유","body":"실프는 중계기 상자의 이동 기록을 현장과 실시간으로 공유했어요.","sentiment":1},{"symbol":"BALL","headline":"상자 색상 표기 교체","body":"몬스터볼 팩토리는 비슷한 상자를 구분하는 색상 표기를 바꿨어요.","sentiment":0},{"symbol":"ROCKET","headline":"배송 인수 절차 개선","body":"로켓단 홀딩스는 상자 인수 시각을 두 번 확인하는 절차를 넣었어요.","sentiment":0},{"symbol":"CELADON","headline":"납품 확인 창구 단일화","body":"금빛시티 백화점은 행사 물품 확인 창구를 하나로 모았어요.","sentiment":1},{"symbol":"OAK","headline":"표본 상자 회수 성공","body":"오박사연구소는 기록 덕분에 표본 상자를 손상 없이 되찾았어요.","sentiment":1}]'::jsonb),
    (16, '큰 전력 시험에서 광맥은 안정됐지만 중계탑 주변의 오래된 배선이 뜨거워졌어요. 다음 공개 행사는 배선을 교체한 뒤 열기로 결정됐어요.', '[{"symbol":"SILPH","headline":"과열 배선 즉시 차단","body":"실프는 자동 차단 장치가 제때 작동했다고 밝혔어요.","sentiment":0},{"symbol":"BALL","headline":"교체 작업용 보호 볼 공급","body":"몬스터볼 팩토리는 작업 포켓몬용 보호 볼을 현장에 보냈어요.","sentiment":1},{"symbol":"CELADON","headline":"공개 행사 일정 재조정","body":"금빛시티 백화점은 입점 상인과 행사 일정을 다시 맞췄어요.","sentiment":-1},{"symbol":"CENTER","headline":"과열 작업 회복 지원","body":"포켓몬센터는 배선 교체 작업자의 회복 지원을 늘렸어요.","sentiment":1},{"symbol":"ROCKET","headline":"교체 자재 우선 운송","body":"로켓단 홀딩스는 배선 자재 운송을 다른 물량보다 앞당겼어요.","sentiment":1}]'::jsonb),
    (17, '배선 교체 공사 중 협곡 길이 좁아져 관광객 동선이 한동안 멈췄어요. 지역 상점은 대신 마을 안쪽 체험 코너를 늘리며 손님을 맞았어요.', '[{"symbol":"SILPH","headline":"공사 구간 안내 지도 배포","body":"실프는 휴대용 지도에 우회 동선을 바로 반영했어요.","sentiment":0},{"symbol":"BALL","headline":"마을 체험 코너로 물량 이동","body":"몬스터볼 팩토리는 협곡 판매 물량을 마을 체험 코너로 옮겼어요.","sentiment":0},{"symbol":"CENTER","headline":"혼잡 구간 이동 진료","body":"포켓몬센터는 줄이 길어진 마을 입구에 이동 진료소를 뒀어요.","sentiment":1},{"symbol":"OAK","headline":"공사 소음 관찰 기록","body":"오박사연구소는 공사 시간과 야생 포켓몬 반응을 함께 기록했어요.","sentiment":0},{"symbol":"ROCKET","headline":"소형 수레 배송 전환","body":"로켓단 홀딩스는 큰 차량 대신 소형 수레로 배송을 바꿨어요.","sentiment":1}]'::jsonb),
    (18, '교체된 배선에서 나온 잔열이 밤하늘에 작은 빛무리를 만들었어요. 마을은 이를 안전한 관찰 행사로 바꾸되 협곡 안쪽 출입은 계속 제한했어요.', '[{"symbol":"SILPH","headline":"빛무리 관찰 신호 개방","body":"실프는 안전 구역에서만 볼 수 있는 관찰 신호를 열었어요.","sentiment":1},{"symbol":"BALL","headline":"야간 관찰 세트 판매","body":"몬스터볼 팩토리는 손전등과 보호 볼을 묶은 세트를 냈어요.","sentiment":1},{"symbol":"CENTER","headline":"야간 귀가 안내 강화","body":"포켓몬센터는 어린 트레이너의 귀가 안내 인력을 늘렸어요.","sentiment":1},{"symbol":"CELADON","headline":"빛무리 사진관 인기","body":"금빛시티 백화점은 마을 사진관과 함께 야간 코너를 열었어요.","sentiment":2},{"symbol":"OAK","headline":"잔열 빛무리 원인 설명","body":"오박사연구소는 빛무리가 위험 신호가 아니라는 관측 결과를 냈어요.","sentiment":2}]'::jsonb),
    (19, '관찰 행사 첫날 예상보다 많은 사람이 모였지만, 입장 시간을 나누자 혼잡이 빠르게 줄었어요. 협곡 전력망은 처음으로 밤새 안정된 출력을 보였어요.', '[{"symbol":"BALL","headline":"입장 시간별 체험 볼 분배","body":"몬스터볼 팩토리는 시간표에 맞춰 체험 볼을 나눠 혼잡을 줄였어요.","sentiment":1},{"symbol":"CENTER","headline":"대기 줄 회복 부스 호평","body":"포켓몬센터의 간단한 회복 부스가 긴 대기 줄에서 호평을 받았어요.","sentiment":1},{"symbol":"CELADON","headline":"야간 상점가 매출 회복","body":"금빛시티 백화점은 늦은 시간 상점가 방문이 늘었다고 전했어요.","sentiment":2},{"symbol":"OAK","headline":"밤샘 출력 안정 기록","body":"오박사연구소는 전력망의 안정 기록을 다음 시험 기준으로 삼았어요.","sentiment":2},{"symbol":"ROCKET","headline":"셔틀 증편으로 혼잡 완화","body":"로켓단 홀딩스는 귀가 셔틀을 늘려 막차 혼잡을 줄였어요.","sentiment":1}]'::jsonb),
    (20, '안정된 출력 소식 뒤에 협곡 외곽의 작은 창고에서 허가 표지가 없는 장비가 발견됐어요. 장비는 바로 회수됐고 공개 행사와는 무관하다고 확인됐어요.', '[{"symbol":"SILPH","headline":"정식 장비 식별표 강화","body":"실프는 현장 장비의 식별표를 다시 확인할 수 있게 했어요.","sentiment":0},{"symbol":"CENTER","headline":"공개 행사 안전 확인","body":"포켓몬센터는 행사 진료 구역이 문제 장비와 무관하다고 안내했어요.","sentiment":0},{"symbol":"CELADON","headline":"입점 장비 반입 재점검","body":"금빛시티 백화점은 행사장 반입 장비의 확인 절차를 한 번 더 거쳤어요.","sentiment":0},{"symbol":"OAK","headline":"미등록 장비 성분 조사","body":"오박사연구소는 장비가 생태에 남긴 흔적이 없는지 조사했어요.","sentiment":-1},{"symbol":"ROCKET","headline":"외곽 창고 관리 논란","body":"로켓단 홀딩스는 임차 창고 관리 기록을 공개하며 확인에 협조했어요.","sentiment":-2}]'::jsonb),
    (21, '장비 점검이 끝난 뒤 협곡 전력망은 다시 시험을 통과했어요. 마을 대표들은 다음 주를 정식 개통 주간으로 정하고 체험 행사를 준비했어요.', '[{"symbol":"SILPH","headline":"전력망 재시험 통과","body":"실프는 점검 뒤 모든 중계 신호가 정상으로 돌아왔다고 밝혔어요.","sentiment":2},{"symbol":"BALL","headline":"개통 주간 물량 확정","body":"몬스터볼 팩토리는 체험 행사 물량을 확정하고 출하를 시작했어요.","sentiment":2},{"symbol":"CELADON","headline":"개통 기념 상점가 공개","body":"금빛시티 백화점은 지역 장인과 함께할 상점가 지도를 공개했어요.","sentiment":2},{"symbol":"OAK","headline":"생태 보호 구역 확정","body":"오박사연구소는 개통 뒤에도 지킬 보호 구역을 정했어요.","sentiment":2},{"symbol":"ROCKET","headline":"셔틀 안전 점검 완료","body":"로켓단 홀딩스는 개통 주간 셔틀의 안전 점검을 마쳤어요.","sentiment":1}]'::jsonb),
    (22, '개통 주간 전날, 광맥의 빛이 잠시 꺼졌다가 새벽에 다시 켜졌어요. 전문가들은 저장된 전력이 자동 조절된 결과라며 차분히 원인을 확인하고 있어요.', '[{"symbol":"SILPH","headline":"자동 조절 기록 분석","body":"실프는 꺼짐과 재점등 사이의 신호 기록을 분석 중이에요.","sentiment":0},{"symbol":"BALL","headline":"행사 물량 출하 보류","body":"몬스터볼 팩토리는 확인이 끝날 때까지 일부 물량의 출하를 늦췄어요.","sentiment":-1},{"symbol":"CENTER","headline":"개통 전 진료 인력 유지","body":"포켓몬센터는 일정 변경 없이 현장 인력을 유지했어요.","sentiment":0},{"symbol":"CELADON","headline":"개통 기념 예약 유지","body":"금빛시티 백화점은 취소 대신 예약자에게 상황을 알렸어요.","sentiment":0},{"symbol":"OAK","headline":"광맥 휴지 현상 설명","body":"오박사연구소는 장치가 스스로 열을 식힌 것으로 보인다고 전했어요.","sentiment":1}]'::jsonb),
    (23, '새벽 분석 결과 광맥은 일정 시간 쉬어야 더 오래 안정되는 것으로 나타났어요. 개통 주간은 하루 늦춰졌지만 운영 시간표는 더 안전하게 다시 짜였어요.', '[{"symbol":"SILPH","headline":"안정 운전 시간표 공개","body":"실프는 쉬는 시간을 반영한 신호 운전표를 공개했어요.","sentiment":1},{"symbol":"BALL","headline":"시간표 맞춘 출하 재개","body":"몬스터볼 팩토리는 새 운영 시간에 맞춰 출하를 다시 시작했어요.","sentiment":1},{"symbol":"CENTER","headline":"야간 진료 순서 조정","body":"포켓몬센터는 관찰 시간에 맞춰 야간 진료 순서를 바꿨어요.","sentiment":1},{"symbol":"CELADON","headline":"개통 행사 하루 순연","body":"금빛시티 백화점은 행사 일정을 하루 미루고 예약을 유지했어요.","sentiment":-1},{"symbol":"ROCKET","headline":"셔틀 시간표 즉시 교체","body":"로켓단 홀딩스는 새 운전표에 맞춰 셔틀 시간을 빠르게 바꿨어요.","sentiment":1}]'::jsonb),
    (24, '정식 개통 첫날, 협곡 전력으로 켜진 길안내등이 밤길을 밝게 비췄어요. 제한된 시간표를 지킨 덕분에 큰 혼잡 없이 첫날을 마쳤어요.', '[{"symbol":"SILPH","headline":"길안내등 첫 점등 성공","body":"실프의 신호 장치가 안내등과 안정적으로 연동됐어요.","sentiment":2},{"symbol":"BALL","headline":"개통 기념 포획 체험","body":"몬스터볼 팩토리는 안전 구역에서 포획 체험을 진행했어요.","sentiment":2},{"symbol":"CENTER","headline":"첫날 무사 진료 마감","body":"포켓몬센터는 큰 부상 없이 첫날 진료를 마쳤어요.","sentiment":2},{"symbol":"OAK","headline":"보호 구역 첫 순찰 완료","body":"오박사연구소는 보호 구역 순찰이 계획대로 끝났다고 전했어요.","sentiment":1},{"symbol":"ROCKET","headline":"귀가 셔틀 만석 운행","body":"로켓단 홀딩스는 정해진 시간표대로 귀가 셔틀을 운행했어요.","sentiment":1}]'::jsonb),
    (25, '개통 이틀째에는 여행객이 예상보다 늘어 협곡 바깥 마을까지 활기가 번졌어요. 운영진은 인기를 이유로 휴지 시간을 줄이지 않겠다고 다시 밝혔어요.', '[{"symbol":"BALL","headline":"초보 트레이너 세트 추가 생산","body":"몬스터볼 팩토리는 처음 찾은 여행객을 위한 세트를 더 만들었어요.","sentiment":2},{"symbol":"CENTER","headline":"마을 진료소 연장 운영","body":"포켓몬센터는 늦게 돌아오는 여행객을 위해 진료 시간을 늘렸어요.","sentiment":1},{"symbol":"CELADON","headline":"지역 상점가 방문 급증","body":"금빛시티 백화점은 협곡 밖 상점가 방문도 늘었다고 전했어요.","sentiment":2},{"symbol":"OAK","headline":"휴지 시간 유지 권고","body":"오박사연구소는 광맥과 야생 포켓몬을 위해 휴지 시간을 지켜 달라고 했어요.","sentiment":0},{"symbol":"ROCKET","headline":"짐 보관소 추가 개설","body":"로켓단 홀딩스는 마을 입구에 임시 짐 보관소를 열었어요.","sentiment":1}]'::jsonb),
    (26, '운영 사흘째, 협곡 안쪽에서 작은 불빛 포켓몬 무리가 길안내등 주위를 맴돌았어요. 길을 막지는 않았지만 관찰 구간을 넓혀야 한다는 의견이 나왔어요.', '[{"symbol":"SILPH","headline":"안내등 밝기 낮춰 조정","body":"실프는 불빛 포켓몬을 자극하지 않도록 안내등 밝기를 낮췄어요.","sentiment":0},{"symbol":"CENTER","headline":"관찰 구간 휴식 안내","body":"포켓몬센터는 관찰 구간에서 지친 포켓몬을 위한 휴식 안내를 냈어요.","sentiment":1},{"symbol":"CELADON","headline":"야간 관찰 상품 수정","body":"금빛시티 백화점은 관찰 구간을 피해 체험 상품 동선을 바꿨어요.","sentiment":0},{"symbol":"OAK","headline":"불빛 포켓몬 서식 확인","body":"오박사연구소는 무리가 원래 이곳에 살았다는 기록을 확인했어요.","sentiment":2},{"symbol":"ROCKET","headline":"셔틀 정차 위치 변경","body":"로켓단 홀딩스는 관찰 구간을 피해 정차 위치를 옮겼어요.","sentiment":0}]'::jsonb),
    (27, '관찰 구간 조정 뒤 불빛 포켓몬 무리는 길안내등과 나란히 이동하기 시작했어요. 마을은 이 장면을 과장하지 않고 조용한 관찰 시간으로 남기기로 했어요.', '[{"symbol":"SILPH","headline":"안내등 이동 패턴 기록","body":"실프는 포켓몬 무리와 안내등의 움직임을 기록하는 모드를 켰어요.","sentiment":1},{"symbol":"BALL","headline":"조용한 관찰 도구 판매","body":"몬스터볼 팩토리는 소리를 줄인 관찰 도구를 별도 코너에 뒀어요.","sentiment":1},{"symbol":"CELADON","headline":"과장 홍보 자제 결정","body":"금빛시티 백화점은 관찰 시간을 할인 행사로 쓰지 않기로 했어요.","sentiment":0},{"symbol":"OAK","headline":"공존 관찰 노트 배포","body":"오박사연구소는 방문객에게 관찰 규칙 노트를 나눠 줬어요.","sentiment":2},{"symbol":"ROCKET","headline":"조용한 셔틀 운행","body":"로켓단 홀딩스는 관찰 시간에 경적을 쓰지 않는 운행을 시작했어요.","sentiment":1}]'::jsonb),
    (28, '마을 대표들은 첫 개통 주간의 기록을 공개하며 다음 달에는 소규모 예약제로 운영하겠다고 했어요. 갑작스러운 인파보다 안전한 반복 운영을 택한 결정이에요.', '[{"symbol":"SILPH","headline":"예약 신호 시스템 제안","body":"실프는 방문 시간을 나누는 간단한 예약 신호 시스템을 제안했어요.","sentiment":1},{"symbol":"BALL","headline":"예약 물량 기준 마련","body":"몬스터볼 팩토리는 예약 수에 맞춰 체험 볼을 준비하기로 했어요.","sentiment":1},{"symbol":"CENTER","headline":"예약 진료 연계 검토","body":"포켓몬센터는 이동이 어려운 방문객의 진료 예약 연계를 검토해요.","sentiment":1},{"symbol":"OAK","headline":"다음 달 관찰 기준 발표","body":"오박사연구소는 다음 달에도 지킬 생태 관찰 기준을 발표했어요.","sentiment":2},{"symbol":"ROCKET","headline":"예약 셔틀 운행 검토","body":"로켓단 홀딩스는 수요에 맞춘 예약 셔틀 운행을 검토해요.","sentiment":1}]'::jsonb),
    (29, '한 달의 끝에서 협곡 전력망은 정해진 휴지 시간과 함께 안정적으로 작동했어요. 탐사대는 광맥을 소유하지 않고 공동 관리하겠다는 원칙을 문서로 남겼어요.', '[{"symbol":"SILPH","headline":"공동 관리 신호망 인계","body":"실프는 마을 관리자가 쓸 신호망 운영 교육을 시작했어요.","sentiment":2},{"symbol":"BALL","headline":"지역 정비소 부품 공급","body":"몬스터볼 팩토리는 멀리서 오지 않아도 되도록 정비 부품을 남겼어요.","sentiment":1},{"symbol":"CENTER","headline":"공동 관리 건강 지침","body":"포켓몬센터는 야간 운영자를 위한 회복 지침을 함께 배포했어요.","sentiment":1},{"symbol":"CELADON","headline":"지역 장인 정기 입점 약속","body":"금빛시티 백화점은 개통 주간 뒤에도 지역 장인 코너를 유지하기로 했어요.","sentiment":2},{"symbol":"ROCKET","headline":"공동 관리 물류 협약 참여","body":"로켓단 홀딩스는 운송 기록을 공동 관리표에 올리기로 했어요.","sentiment":1}]'::jsonb)
), entries as (
  select day_offset, context, entry.value, entry.ordinality
  from stories cross join lateral jsonb_array_elements(entries) with ordinality as entry(value, ordinality)
)
insert into public.trainer_market_news_pool (market_date, publish_order, symbol, headline, body, sentiment)
select
  (now() at time zone 'Asia/Seoul')::date + day_offset,
  ordinality,
  value ->> 'symbol',
  value ->> 'headline',
  concat(context, ' ', value ->> 'body'),
  (value ->> 'sentiment')::smallint
from entries;
